name: CI

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) 리포지토리 체크아웃
      - uses: actions/checkout@v4

      # 2) Node 설정
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      # 3) 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 4) Prisma generate
      - name: Prisma Generate
        run: npx prisma generate

      # 5) Nest build
      - name: Build Project
        run: npm run build
